# Generated by Django 5.0.7 on 2024-07-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blog_DB',
        ),
        migrations.RenameIndex(
            model_name='blog_db',
            new_name='blog_blog_d_publish_7ed2ca_idx',
            old_name='blog_blog_publish_79f1b4_idx',
        ),
        migrations.RenameIndex(
            model_name='blog_db',
            new_name='blog_blog_d_slug_7989e2_idx',
            old_name='blog_blog_slug_d925e3_idx',
        ),
    ]
