# Generated by Django 5.0.7 on 2024-07-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_blog_db_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_DB',
            new_name='BlogDb',
        ),
        migrations.RenameIndex(
            model_name='blogdb',
            new_name='blog_blogdb_publish_f8b424_idx',
            old_name='blog_blog_d_publish_7ed2ca_idx',
        ),
        migrations.RenameIndex(
            model_name='blogdb',
            new_name='blog_blogdb_slug_933d0b_idx',
            old_name='blog_blog_d_slug_7989e2_idx',
        ),
    ]
