# Generated by Django 5.0.7 on 2024-07-22 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrestapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='name',
        ),
    ]
